name: website deploy preview
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn build
        env:
          API_URL: ${{ secrets.API_URL }}
          FIREBASE_CERT: ${{ secrets.FIREBASE_CERT }}
          FIREBASE_CLIENT_CONFIG: ${{ secrets.FIREBASE_CLIENT_CONFIG }}
          IFRAME_URL: ${{ secrets.IFRAME_URL }}
          
      - uses: amondnet/vercel-action@v20
        env:
          FIREBASE_CERT: ${{ secrets.FIREBASE_CERT }}
          FIREBASE_CLIENT_CONFIG: ${{ secrets.FIREBASE_CLIENT_CONFIG }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./website/.next
          
